query {
  pages {
    list {
      id
      locale
      path
      title
      description
      contentType
      isPublished
      isSubmit
      isPrivate
      privateNS
      createdAt
      updatedAt
    }
  }
}
